# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb3e85d01989aa2d6f08378b8df5a312"
name = "spector"
handle = "spector-1"
application_url = "https://humanities-registered-astronomy-matters.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = ["https://humanities-registered-astronomy-matters.trycloudflare.com/auth/callback", "https://humanities-registered-astronomy-matters.trycloudflare.com/auth/shopify/callback", "https://humanities-registered-astronomy-matters.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
